# Generated by Django 4.1.2 on 2022-11-02 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l5', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='bought',
        ),
    ]
