# Generated by Django 4.1.2 on 2022-11-02 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l5', '0002_remove_purchase_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='idclient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bag_client', to='l5.client', verbose_name='idClient'),
        ),
    ]
