# Generated by Django 4.1.2 on 2022-11-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l5', '0004_remove_purchase_date_bag_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='current_bag',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bag',
            name='sum',
            field=models.IntegerField(default=0),
        ),
    ]
