# Generated by Django 4.1.2 on 2022-11-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l5', '0009_alter_bag_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='current_bag',
        ),
        migrations.AlterField(
            model_name='client',
            name='clientid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='clientname',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='login',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
