# Generated by Django 3.2.16 on 2022-11-19 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('l5', '0010_remove_client_current_bag_alter_client_clientid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='idclient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bag_client', to=settings.AUTH_USER_MODEL, verbose_name='idClient'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
